title: Ball Hill Lagrangian
author:
  name: Benjamin Robbins
  email:
  github:
description: This program simulates a ball moving down a hill using Lagrangian Dynamics.
language: C++
image:
  icon: https://cloud.githubusercontent.com/assets/10502938/13506660/28be0300-e14d-11e5-90e3-b194f14e52bd.PNG
  banner: https://cloud.githubusercontent.com/assets/10502938/13506660/28be0300-e14d-11e5-90e3-b194f14e52bd.PNG
tags:
  - C++
  - Physics
  - Lagrangian Dynamics
extra_resources:
connections: